# Generated by Django 2.1.1 on 2018-11-12 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretpawapp', '0002_auto_20181112_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='facebook',
            field=models.URLField(max_length=500, unique=True),
        ),
    ]
