# Generated by Django 2.1.1 on 2018-12-18 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('secretpawapp', '0004_profile_is_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(null=True, upload_to='')),
                ('picture_author', models.CharField(blank=True, max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('age', models.PositiveIntegerField()),
                ('race', models.CharField(blank=True, max_length=50)),
                ('sex', models.CharField(choices=[('W', 'Girl'), ('M', 'Boy'), ('O', 'Other')], max_length=1)),
                ('description', models.TextField(blank=True, max_length=250)),
                ('hints', models.TextField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='')),
                ('wishes', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of site-wide variable', max_length=200, unique=True)),
                ('value', models.CharField(blank=True, help_text='Value of site-wide variable that scripts can reference', max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='description',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='profile',
            name='facebook',
            field=models.URLField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='gift',
            name='giver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='giver', to='secretpawapp.Profile'),
        ),
        migrations.AddField(
            model_name='gift',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='recipient', to='secretpawapp.Profile'),
        ),
        migrations.AddField(
            model_name='character',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secretpawapp.Profile'),
        ),
        migrations.AddField(
            model_name='character',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secretpawapp.Tag'),
        ),
        migrations.AddField(
            model_name='profile',
            name='tags',
            field=models.ManyToManyField(to='secretpawapp.Tag'),
        ),
    ]
