# Generated by Django 2.1.1 on 2018-12-18 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretpawapp', '0005_auto_20181218_1434'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterNSFWTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='nsfw',
            field=models.ManyToManyField(to='secretpawapp.CharacterNSFWTypes'),
        ),
    ]
