# Generated by Django 2.1.1 on 2018-12-23 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('secretpawapp', '0007_auto_20181223_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='giver',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='giver', to='secretpawapp.Profile'),
        ),
        migrations.AlterField(
            model_name='gift',
            name='recipient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='recipient', to='secretpawapp.Profile'),
        ),
        migrations.AlterField(
            model_name='gift',
            name='wishes',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
