# Generated by Django 2.1.1 on 2018-12-23 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretpawapp', '0009_auto_20181223_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='picture',
            field=models.ImageField(null=True, upload_to='secretpawapp/static/file/character'),
        ),
        migrations.AlterField(
            model_name='character',
            name='picture_author',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='gift',
            name='picture',
            field=models.ImageField(upload_to='secretpawapp/static/file/gift'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(null=True, upload_to='secretpawapp/static/file/avatar'),
        ),
    ]
