# Generated by Django 2.1.1 on 2018-12-27 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('secretpawapp', '0013_auto_20181223_2131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='nsfw',
        ),
        migrations.AddField(
            model_name='character',
            name='nsfw',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='secretpawapp.CharacterNSFWTypes'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='character',
            name='picture',
            field=models.ImageField(null=True, upload_to='character'),
        ),
        migrations.AlterField(
            model_name='gift',
            name='picture',
            field=models.ImageField(upload_to='gift'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(null=True, upload_to='avatar'),
        ),
    ]
