# Generated by Django 2.1.1 on 2019-01-05 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('secretpawapp', '0017_auto_20181227_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='characters',
        ),
        migrations.AddField(
            model_name='character',
            name='owner',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='secretpawapp.Profile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='character',
            name='nsfw',
            field=models.ManyToManyField(blank=True, to='secretpawapp.CharacterNSFWTypes'),
        ),
        migrations.AlterField(
            model_name='character',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secretpawapp.Tag'),
        ),
    ]
