# Generated by Django 2.1.5 on 2019-01-13 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretpawapp', '0018_auto_20190105_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='gift'),
        ),
        migrations.AlterField(
            model_name='gift',
            name='wishes',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
