# Generated by Django 2.1.5 on 2019-01-13 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('secretpawapp', '0019_auto_20190113_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='giver',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='giver', to='secretpawapp.Profile'),
        ),
        migrations.AlterField(
            model_name='gift',
            name='recipient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recipient', to='secretpawapp.Profile'),
        ),
        # migrations.RunSQL("""
        #     ALTER TABLE secretpawapp_gift add constraint match_giver_and_recipient_not_equal check (giver <> recipient);
        # """),
    ]
