# Generated by Django 2.1.5 on 2019-04-10 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretpawapp', '0020_auto_20190113_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='age',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='picture',
            field=models.ImageField(default=None, upload_to='character'),
            preserve_default=False,
        ),
    ]
