# Generated by Django 2.1.5 on 2019-04-10 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretpawapp', '0021_auto_20190410_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='age',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
