# Generated by Django 2.1.5 on 2019-04-12 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretpawapp', '0022_auto_20190410_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='sex',
            field=models.CharField(choices=[('W', 'Girl'), ('M', 'Men'), ('O', 'Other')], max_length=1),
        ),
    ]
